<a href="https://colab.research.google.com/github/Musu1/Deep-Learning/blob/master/pytorch_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import torch
import numpy as np
import matplotlib.pyplot as plt

# **Initialise tensors**

In [87]:
# x is of tensor datatype
x=torch.ones(3,2)
print(x)
x=torch.zeros(3,2)
print(x)
x=torch.rand(3,2)
print(x)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])
tensor([[0.5120, 0.4467],
        [0.3735, 0.9256],
        [0.7119, 0.2485]])


In [88]:
x=torch.empty(3,2)
print(x)
# If _like is used then we don't have to mention datatype
y=torch.rand_like(x)
print(y)
y=torch.ones_like(x)
print(y)

tensor([[-2.3725e+22,  0.0000e+00],
        [ 4.4842e-44,  0.0000e+00],
        [        nan,  0.0000e+00]])
tensor([[0.8280, 0.2161],
        [0.4093, 0.7944],
        [0.5492, 0.7487]])
tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])


In [89]:
x=torch.linspace(0,1,15)
print(x)

tensor([0.0000, 0.0714, 0.1429, 0.2143, 0.2857, 0.3571, 0.4286, 0.5000, 0.5714,
        0.6429, 0.7143, 0.7857, 0.8571, 0.9286, 1.0000])


In [90]:
x=torch.tensor([[3,2],[5,4],[7,6]])
print(x)

tensor([[3, 2],
        [5, 4],
        [7, 6]])


# **Slicing the tensors**

In [91]:
# Slicing is same as pytorch
print(x.size())
print(x[:,0])
print(x[2,:])

torch.Size([3, 2])
tensor([3, 5, 7])
tensor([7, 6])


In [92]:
print(x[0:2,0])
print(x[0:3,1])

tensor([3, 5])
tensor([2, 4, 6])


In [93]:
#By using item we convert from tensor data type to digit
y=x[2,1]
print(y)
print(y.item())

tensor(6)
6


# Reshaping the tensors

In [94]:
#view is used to reshape the tensors
print(x)
y=x.view(2,3)
print(y)

tensor([[3, 2],
        [5, 4],
        [7, 6]])
tensor([[3, 2, 5],
        [4, 7, 6]])


In [95]:
#If -1 is specified then only one of the size need to be mentioned ,other will be decided accordingly
y=x.view(6,-1)
print(y)

tensor([[3],
        [2],
        [5],
        [4],
        [7],
        [6]])


In [96]:
y=x.view(3,-1)
print(y)

tensor([[3, 2],
        [5, 4],
        [7, 6]])


# Simple tensor operations

In [97]:
x=torch.ones(3,2)
y=torch.ones(3,2)
z=x+y
print(z)
z=x-y
print(z)
z=x*y
print(z)

tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])
tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])
tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])


In [98]:
z=x.add(y)
print(z)
print(x)

tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])
tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])


In [99]:
# add_ is used then 
z=x.add_(y)
print(z)
print(x)

tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])
tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])


# Numpy Vs Pytorch

In [100]:
#converting from tensor to numpy
print(x)
x_np=x.numpy()
print(type(x),type(x_np))
print(x_np)

tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])
<class 'torch.Tensor'> <class 'numpy.ndarray'>
[[2. 2.]
 [2. 2.]
 [2. 2.]]


In [101]:
#numpy array to tensor datatype
a=np.random.randn(5)
print(a)
a_pt=torch.from_numpy(a)
print(type(a),type(a_pt))
print(a_pt)

[-0.48359666  0.14246943  1.24944953  0.37444187  0.81015037]
<class 'numpy.ndarray'> <class 'torch.Tensor'>
tensor([-0.4836,  0.1425,  1.2494,  0.3744,  0.8102], dtype=torch.float64)


In [102]:
np.add(a,1,out=a)
print(a)
print(a_pt)

[0.51640334 1.14246943 2.24944953 1.37444187 1.81015037]
tensor([0.5164, 1.1425, 2.2494, 1.3744, 1.8102], dtype=torch.float64)


In [103]:
#Any operation using tensors take less time then using numpy arrays 
%%time
for i in range(100):
  a=np.random.randn(100,100)
  b=np.random.randn(100,100)
  c=a+b

CPU times: user 102 ms, sys: 1.92 ms, total: 104 ms
Wall time: 112 ms


In [104]:
%%time
for i in range(100):
  a=torch.tensor([100,100])
  b=torch.tensor([100,100])
  c=a+b

CPU times: user 2.53 ms, sys: 11 µs, total: 2.54 ms
Wall time: 2.83 ms


In [105]:
%%time
for i in range(100):
  a=np.random.randn(100,100)
  b=np.random.randn(100,100)
  c=a*b

CPU times: user 93.6 ms, sys: 0 ns, total: 93.6 ms
Wall time: 94.6 ms


In [106]:
%%time
for i in range(100):
  a=torch.tensor([100,100])
  b=torch.tensor([100,100])
  c=a*b

CPU times: user 1.35 ms, sys: 959 µs, total: 2.31 ms
Wall time: 2.53 ms


In [107]:
%%time
for i in range(100):
  a=np.random.randn(100,100)
  b=np.random.randn(100,100)
  c=np.matmul(a,b)

CPU times: user 167 ms, sys: 109 ms, total: 276 ms
Wall time: 149 ms


In [108]:
%%time
for i in range(100):
  a=torch.tensor([100,100])
  b=torch.tensor([100,100])
  c=torch.matmul(a,b)

CPU times: user 2.45 ms, sys: 9 µs, total: 2.46 ms
Wall time: 2.63 ms


# Cuda Support

In [109]:
#This command tells us if you have any GPUS in your suystem
#Cuda is language extension by nvidia to program in GPUs dfirectly
#So this command will tell us how many cuda supported devices we have?
print(torch.cuda.device_count())

1


In [110]:
#This will tell us the cuda device location and name
print(torch.cuda.device(0))
print(torch.cuda.get_device_name(0))

Tesla K80


In [0]:
#Now we can reference the device at location 0 with cuda0 
cuda0=torch.device('cuda:0')

In [112]:
#Now to do the operation in GPU instead of CPU we use the reference above
%%time
for i in range(100):
  a=torch.ones(3,2,device=cuda0)
  b=torch.ones(3,2,device=cuda0)
  c=a+b
print(c)

tensor([[2., 2.],
        [2., 2.],
        [2., 2.]], device='cuda:0')
CPU times: user 9.12 ms, sys: 14 ms, total: 23.1 ms
Wall time: 21.8 ms


In [113]:
#we have already seen that pytorch do operation about 3 to 5 times faster then numpy but here the GPU support do it 1000 time faster
%%time
for i in range(10):
  a=np.random.randn(10000,10000)
  b=np.random.randn(10000,10000)
  np.add(b,a)

CPU times: user 1min 32s, sys: 251 ms, total: 1min 32s
Wall time: 1min 32s


In [114]:
%%time
for i in range(10):
  a_cpu=torch.randn([10000,10000])
  b_cpu=torch.randn([10000,10000])
  b_cpu.add_(a_cpu)

CPU times: user 23.3 s, sys: 8.57 ms, total: 23.3 s
Wall time: 23.4 s


In [115]:
%%time
for i in range(10):
  a=torch.randn([10000,10000],device=cuda0)
  b=torch.randn([10000,10000],device=cuda0)
  b.add_(a)
  

CPU times: user 1.09 ms, sys: 987 µs, total: 2.07 ms
Wall time: 1.85 ms


# Autograd

In [116]:
#Autograd calculates the gradient automatically. We won't have to the forward and backward pass like we are doing till now manually.
#requires_grad is used with the variable with respect to which we calculate differentiation
x=torch.ones([3,2],requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]], requires_grad=True)


In [117]:
# We have started the forward pass
y=x+5
print(y)

tensor([[6., 6.],
        [6., 6.],
        [6., 6.]], grad_fn=<AddBackward0>)


In [118]:
z=y*y+1
print(z)

tensor([[37., 37.],
        [37., 37.],
        [37., 37.]], grad_fn=<AddBackward0>)


In [119]:
t=torch.sum(z)
print(t)

tensor(222., grad_fn=<SumBackward0>)


In [0]:
#Now we do the backward pass we won't get output right now but here it calculates the differentiations automatically
t.backward()

In [121]:
print(x.grad)

tensor([[12., 12.],
        [12., 12.],
        [12., 12.]])


In [122]:
#In both these examples we have used torch.sum before backward function because we need to use a parameter in the fxn if we are doing backward pass on tensor not on no.
x=torch.ones([3,2],requires_grad=True)
y=x+5
r=1/(1+torch.exp(-y))
print(r)
s=torch.sum(r)
s.backward()
print(x.grad)

tensor([[0.9975, 0.9975],
        [0.9975, 0.9975],
        [0.9975, 0.9975]], grad_fn=<MulBackward0>)
tensor([[0.0025, 0.0025],
        [0.0025, 0.0025],
        [0.0025, 0.0025]])


In [123]:
#So here we are using a parameter in backward function because here backward pass is done on a tensor
#we have used a to do a point multiplication with r and since it is one so won't affect
x=torch.ones([3,2],requires_grad=True)
y=x+5
r=1/(1+torch.exp(-y))
print(r)
a=torch.ones([3,2])
r.backward(a)
print(x.grad)

tensor([[0.9975, 0.9975],
        [0.9975, 0.9975],
        [0.9975, 0.9975]], grad_fn=<MulBackward0>)
tensor([[0.0025, 0.0025],
        [0.0025, 0.0025],
        [0.0025, 0.0025]])


# Autograd Example

In [0]:
#So here we would compute loss to see how we can use autograd with neural network
x=torch.randn([20,1],requires_grad=True) # Input to the neural net
y=3*x-2 # Actual output

In [0]:
w=torch.tensor([.1],requires_grad=True)
b=torch.tensor([.1],requires_grad=True)
y_hat=w*x+b
loss=torch.sum((y_hat-y)**2)

In [126]:
#We can see loss is too large because we have assumed w and b as 1 but really it is 3 and -2
print(loss)

tensor(304.0748, grad_fn=<SumBackward0>)


In [0]:
loss.backward()

In [128]:
#Here the w gradient is negative because as we increase weight loss will decrease and b gradient is positive because as we increase bias loss will increase
print(w.grad,b.grad)

tensor([-131.3526]) tensor([108.2033])


# Do it in a loop

In [129]:
learning_rate=0.01

w=torch.tensor([1.],requires_grad=True) # We initialised w=1
b=torch.tensor([1.],requires_grad=True) # We initialised b=1

print(w.item(),b.item())

for i in range(10):
  x=torch.randn([20,1]) # Input variables
  y=3*x-2               # Output variable
  y_hat=w*x+b           # Predicted values
  loss=torch.sum((y_hat-y)**2) #Loss calculation
  loss.backward()       #calculation loass wrt w and b
  
  #we used torch.no_grad so that it does not bookeep forevery w and b update and in that it will work as normal airthmetic operation
  with torch.no_grad():
    w-=learning_rate*w.grad
    b-=learning_rate*b.grad
    w.grad.zero_()
    b.grad.zero_()
  
  print(w.item(),b.item())

1.0 1.0
1.778407335281372 -0.24135327339172363
2.280791759490967 -0.9031935334205627
2.4622151851654053 -1.342228889465332
2.795983076095581 -1.7079941034317017
2.857198476791382 -1.8053561449050903
2.92468523979187 -1.8912137746810913
2.9553229808807373 -1.9321346282958984
2.96923828125 -1.9575343132019043
2.980092763900757 -1.9759339094161987
2.98529052734375 -1.9835783243179321


In [130]:
%%time

learning_rate=0.001
N=1000
epochs=100

w=torch.randn([N],requires_grad=True)
b=torch.ones([1],requires_grad=True)
#print(torch.mean(w).item(),b.item())

for i in range(epochs):
  x=torch.randn([N])
  y=torch.dot(3*torch.ones([N]),x)-2
  y_hat=torch.dot(w,x)+b
  loss=torch.sum((y_hat-y)**2)
  loss.backward()
  
  with torch.no_grad():
    w-=learning_rate*w.grad
    b-=learning_rate*b.grad
    w.grad.zero_()
    b.grad.zero_()
 # print(w.item(),b.item())

CPU times: user 45.1 ms, sys: 3.61 ms, total: 48.7 ms
Wall time: 50.3 ms


In [131]:
%%time

learning_rate=0.001
N=1000
epochs=100

w=torch.randn([N],requires_grad=True,device=cuda0)
b=torch.ones([1],requires_grad=True,device=cuda0)
#print(torch.mean(w).item(),b.item())

for i in range(epochs):
  x=torch.randn([N],device=cuda0)
  y=torch.dot(3*torch.ones([N],device=cuda0),x)-2
  y_hat=torch.dot(w,x)+b
  loss=torch.sum((y_hat-y)**2)
  loss.backward()
  
  with torch.no_grad():
    w-=learning_rate*w.grad
    b-=learning_rate*b.grad
    w.grad.zero_()
    b.grad.zero_()
 # print(w.item(),b.item())

CPU times: user 239 ms, sys: 114 ms, total: 354 ms
Wall time: 357 ms
